### ISSUE TITLE
Forward and rewind buttons jamming

### ISSUE THREAD

**Issue by Infomir-Android** [salema/PodCatcher-Deluxe-Android#98]
In both audio and video players, if I press and hold 'Foward' (or 'Rewind') button and then move cursor away from the button and then release, player start infinite rewinding the track. This misbehavious continues when I press 'Resume' button, and does not disappear even when I change episode or restart the app. The only way to stop it is stopping application.

**Comment by Infomir-Android** [comment]
Problem is solved by adding to rewindRunnable and forwardRunnable a check if corresponding button isPressed() before posting runnable again to the handler.

**Comment by salema** [comment]
Can you test this on your side and send me a pull request? That would be great!
